{{- if eq (include "vector-aggregator.servicePortsPresent" .) "true" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "libvector.fullname" . }}
  labels:
    {{- include "libvector.labels" . | nindent 4 }}
spec:
<<<<<<< HEAD
  type: {{ default "ClusterIP" .Values.service.type }}
=======
  type: {{ .Values.service.type }}
>>>>>>> upstream/master
  ports:
  {{- include "vector-aggregator.servicePorts" . | nindent 2 }}
  selector:
    {{- include "libvector.selectorLabels" . | nindent 4 }}
{{- end }}
