apiVersion: v1
kind: Service
metadata:
  name: {{ include "libvector.fullname" . }}-headless
  labels:
    {{- include "libvector.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
<<<<<<< HEAD
{{- if .Values.vectorSource.enabled }}
  - name: vector
    port: {{ .Values.vectorSource.listenPort }}
    protocol: TCP
    targetPort: {{ .Values.vectorSource.listenPort }}
{{- end }}
{{- with .Values.service.ports }}
{{ toYaml . | nindent 2 }}
{{- end }}
=======
  {{- include "vector-aggregator.headlessServicePorts" . | nindent 2 }}
>>>>>>> upstream/master
  selector:
    {{- include "libvector.selectorLabels" . | nindent 4 }}
